### ISSUE TITLE
Change Editor in printoption dialog

### ISSUE THREAD

**Issue by lHeidbreder** [Martin-Schoenbeck-Beratungen-GmbH/beluga.serverprint#6]
Printoption dialog uses a dropdown menu.

`Radio Buttons` would be preferable.
Even better still: `Action Buttons`

**Comment by JanSchoenbeck** [comment]
1. Action buttons are difficult to implement because the dialog is not that easy to set up 
2. Radio buttons work without a standard option and without an option to cancel the process
